---
javascripts:
- base:
  - prototype
  - jquery
  - jquery-ui
  - jquery.cookie
  - jrails
  - shadowbox
  - effects
  #- dragdrop
  - controls
  - application
  - cit
  - juggernaut_javascript
  - general
  - swfobject
- widgets:
  - excanvas
  - prototype
  #- effects
  - dragdrop
  #- controls
  - builder
  - portal
  - flotr
- right_column:
  - task_filter
- forums:
  - beast
- login:
  - prototype
  - tz
  - frontpage
#- worklogs: [jscalendar-1.0/calendar, jscalendar-1.0/lang/calendar-en, jscalendar-1.0/calendar-setup]
- worklogs:
  - jscalendar-1.0/calendar
  - jscalendar-1.0/lang/calendar-en
  - jscalendar-1.0/calendar-setup
  - dists/jquery.utils.lite
  - datejs/date
  - datejs/extras
  - durationUtils

stylesheets:
- base:
  - general
  - header
  - footer
  - task
  - cit
  - ui-lightness/jquery-ui
- login:
  - login
- widgets:
  - widget
- forums:
  - beast
#- worklogs: [../javascripts/jscalendar-1.0/calendar-blue]
- worklogs:
  - ../javascripts/jscalendar-1.0/calendar-blue
